include(ExternalProject)

set(ospray_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DOSPRAY_MODULE_DENOISER=ON
    -DOSPRAY_ENABLE_APPS=OFF
    -DEMBREE_ISPC_SUPPORT=ON
    -DEMBREE_FILTER_FUNCTION=ON
    -DEMBREE_GEOMETRY_TRIANGLE=ON
    -DEMBREE_GEOMETRY_CURVE=ON
    -DEMBREE_GEOMETRY_USER=ON
    -DEMBREE_RAY_PACKETS=ON
    -DEMBREE_BACKFACE_CULLING=OFF
    -DEMBREE_MAX_ISA=NONE
    -DEMBREE_ISA_SSE2=ON
    -DEMBREE_ISA_SSE42=ON
    -DEMBREE_ISA_AVX=ON
    -DEMBREE_ISA_AVX2=ON
    -DEMBREE_ISA_AVX512KNL=OFF
    -DEMBREE_ISA_AVX512SKX=OFF)
if(CMAKE_CXX_STANDARD)
    set(ospray_ARGS ${ospray_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
endif()

ExternalProject_Add(
    ospray
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/ospray
    DEPENDS rkcommon embree OpenImageDenoise openvkl
    GIT_REPOSITORY https://github.com/ospray/ospray.git
    GIT_TAG v2.5.0
    GIT_SUBMODULES ""
    PATCH_COMMAND
        ${CMAKE_COMMAND} -E tar xf
        ${CMAKE_SOURCE_DIR}/ospray-patch.tar.gz
    CMAKE_ARGS ${ospray_ARGS})
