include(ExternalProject)

set(OpenCV_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DBUILD_WITH_STATIC_CRT=OFF
    -DBUILD_LIST=calib3d,dnn,features2d,flann,gapi,imgproc,ml,objdetect,photo,stitching,videoio
    -DBUILD_ZLIB=OFF
    -DBUILD_TIFF=OFF
    -DBUILD_JASPER=OFF
    -DBUILD_JPEG=OFF
    -DBUILD_PNG=OFF
    -DBUILD_OPENEXR=OFF
    -DBUILD_WEBP=OFF
    -DWITH_1394=OFF
    -DWITH_AVFOUNDATION=OFF
    -DWITH_CAP_IOS=OFF
    -DWITH_VTK=OFF
    -DWITH_FFMPEG=OFF
    -DWITH_GSTREAMER=OFF
    -DWITH_GTK=OFF
    -DWITH_JASPER=OFF
    -DWITH_OPENJPEG=OFF
    -DWITH_JPEG=OFF
    -DWITH_WEBP=OFF
    -DWITH_OPENEXR=OFF
    -DWITH_PNG=TRUE
    -DWITH_WIN32UI=OFF
    -DWITH_TIFF=OFF
    -DWITH_V4L=OFF
    -DWITH_DSHOW=OFF
    -DWITH_MSMF=OFF
    -DWITH_IMGCODEC_HDR=OFF
    -DWITH_IMGCODEC_SUNRASTER=OFF
    -DWITH_IMGCODEC_PXM=OFF
    -DWITH_IMGCODEC_PFM=OFF
    -DWITH_IPP=OFF
    -DWITH_ITT=OFF)
if(CMAKE_CXX_STANDARD)
    set(OpenCV_ARGS ${OpenCV_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
endif()

ExternalProject_Add(
    OpenCV
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/OpenCV
    DEPENDS ZLIB
    GIT_REPOSITORY "https://github.com/opencv/opencv.git"
    GIT_TAG 4.5.0
    CMAKE_ARGS ${OpenCV_ARGS})
