include(ExternalProject)

set(OpenImageIO_BUILD_STATIC OFF)
if(NOT BUILD_SHARED_LIBS)
    set(OpenImageIO_BUILD_STATIC ON)
endif()

set(OpenImageIO_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DOIIO_BUILD_TOOLS=OFF
    -DOIIO_BUILD_TESTS=OFF
    -DBUILD_DOCS=OFF
    -DUSE_PYTHON=OFF
    -DENABLE_BZip2=OFF
    -DENABLE_OpenColorIO=OFF
    -DENABLE_DCMTK=OFF
    -DENABLE_FFmpeg=OFF
    -DENABLE_Field3D=OFF
    -DENABLE_Freetype=OFF
    -DENABLE_GIF=OFF
    -DENABLE_Libheif=OFF
    -DENABLE_LibRaw=OFF
    -DENABLE_OpenJpeg=OFF
    -DENABLE_WebP=OFF
    -DENABLE_R3DSDK=OFF
    -DENABLE_Nuke=OFF
    -DENABLE_OpenGL=OFF
    -DENABLE_Qt5=OFF
    -DENABLE_Libsquish=OFF
    -DLINKSTATIC=${OpenImageIO_BUILD_STATIC})
if(CMAKE_CXX_STANDARD)
    set(OpenImageIO_ARGS ${OpenImageIO_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
endif()

ExternalProject_Add(
    OpenImageIO
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/OpenImageIO
    DEPENDS ZLIB Boost TIFF OpenEXR JPEG PNG  HDF5 OpenCV TBB OpenVDB Ptex
    GIT_REPOSITORY https://github.com/OpenImageIO/oiio.git
    GIT_TAG Release-2.2.9.0
    PATCH_COMMAND
        ${CMAKE_COMMAND} -E tar xf
        ${CMAKE_SOURCE_DIR}/OpenImageIO-patch.tar.gz
    CMAKE_ARGS ${OpenImageIO_ARGS})
