include(ExternalProject)

set(USD_BUILD_EXAMPLES ON)
set(USD_BUILD_TUTORIALS ON)
set(USD_BUILD_USD_TOOLS ON)
set(USD_ENABLE_PYTHON_SUPPORT OFF)

set(USD_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_PREFIX}/lib
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DPXR_BUILD_TESTS=OFF
    -DPXR_BUILD_EXAMPLES=${USD_BUILD_EXAMPLES}
    -DPXR_BUILD_TUTORIALS=${USD_BUILD_TUTORIALS}
    -DPXR_BUILD_USD_TOOLS=${USD_BUILD_USD_TOOLS}
    -DPXR_BUILD_EMBREE_PLUGIN=ON
    -DPXR_BUILD_OPENIMAGEIO_PLUGIN=ON
    -DPXR_BUILD_OPENCOLORIO_PLUGIN=ON
    -DPXR_BUILD_ALEMBIC_PLUGIN=ON
    -DPXR_BUILD_MATERIALX_PLUGIN=ON
    -DPXR_ENABLE_PYTHON_SUPPORT=${USD_ENABLE_PYTHON_SUPPORT}
    -DPXR_ENABLE_OPENVDB_SUPPORT=ON
    -DBoost_NO_BOOST_CMAKE=OFF)
if(CMAKE_CXX_STANDARD)
    set(USD_ARGS ${USD_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
endif()

ExternalProject_Add(
    USD
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/USD
    DEPENDS embree MaterialX Alembic OpenImageIO OpenVDB OpenColorIO Ptex OpenEXR OpenSubdiv Boost TBB
    GIT_REPOSITORY https://github.com/PixarAnimationStudios/USD.git
    GIT_TAG v21.02
    PATCH_COMMAND
        ${CMAKE_COMMAND} -E tar xf
        ${CMAKE_SOURCE_DIR}/USD-patch.tar.gz
    CMAKE_ARGS ${USD_ARGS})
