include(ExternalProject)

set(EMBREE_STATIC_LIB OFF)
if(NOT BUILD_SHARED_LIBS)
    set(EMBREE_STATIC_LIB ON)
endif()

set(embree_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DEMBREE_STATIC_LIB=${EMBREE_STATIC_LIB}
    -DEMBREE_ISPC_SUPPORT=ON
    -DEMBREE_TUTORIALS=OFF)
if(CMAKE_CXX_STANDARD)
    set(embree_ARGS ${embree_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
endif()

ExternalProject_Add(
    embree
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/embree
    DEPENDS TBB ISPC
    GIT_REPOSITORY https://github.com/embree/embree.git
    GIT_TAG v3.12.1
    PATCH_COMMAND
        ${CMAKE_COMMAND} -E tar xf
        ${CMAKE_SOURCE_DIR}/embree-patch.tar.gz
    CMAKE_ARGS ${embree_ARGS})
