include(ExternalProject)
include(${CMAKE_INSTALL_PREFIX}/lib/cmake/embree-3.12.1/embree-config.cmake)

set(ospray_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DOSPRAY_MODULE_DENOISER=ON
    -DOSPRAY_ENABLE_APPS=OFF)
if(CMAKE_CXX_STANDARD)
    set(ospray_ARGS ${ospray_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
endif()
set(ospray_ARGS
    ${ospray_ARGS}
    -DEMBREE_VERSION=${EMBREE_VERSION}
    -DEMBREE_VERSION_MAJOR=${EMBREE_VERSION_MAJOR}
    -DEMBREE_VERSION_MINOR=${EMBREE_VERSION_MINOR}
    -DEMBREE_VERSION_PATCH=${EMBREE_VERSION_PATCH}
    -DEMBREE_VERSION_NOTE=${EMBREE_VERSION_NOTE}
    -DEMBREE_MAX_ISA=${EMBREE_MAX_ISA}
    -DEMBREE_ISA_SSE2=${EMBREE_ISA_SSE2}
    -DEMBREE_ISA_SSE42=${EMBREE_ISA_SSE42}
    -DEMBREE_ISA_AVX=${EMBREE_ISA_AVX}
    -DEMBREE_ISA_AVX2=${EMBREE_ISA_AVX2}
    -DEMBREE_ISA_AVX512KNL=${EMBREE_ISA_AVX512KNL}
    -DEMBREE_ISA_AVX512SKX=${EMBREE_ISA_AVX512SKX}
    -DEMBREE_BUILD_TYPE=${EMBREE_BUILD_TYPE}
    -DEMBREE_ISPC_SUPPORT=${EMBREE_ISPC_SUPPORT}
    -DEMBREE_STATIC_LIB=${EMBREE_STATIC_LIB}
    -DEMBREE_TUTORIALS=${EMBREE_TUTORIALS}
    -DEMBREE_RAY_MASK=${EMBREE_RAY_MASK}
    -DEMBREE_STAT_COUNTERS=${EMBREE_STAT_COUNTERS}
    -DEMBREE_BACKFACE_CULLING=${EMBREE_BACKFACE_CULLING}
    -DEMBREE_FILTER_FUNCTION=${EMBREE_FILTER_FUNCTION}
    -DEMBREE_IGNORE_INVALID_RAYS=${EMBREE_IGNORE_INVALID_RAYS}
    -DEMBREE_TASKING_SYSTEM=${EMBREE_TASKING_SYSTEM}
    -DEMBREE_COMPACT_POLYS=${EMBREE_COMPACT_POLYS}
    -DEMBREE_GEOMETRY_TRIANGLE=${EMBREE_GEOMETRY_TRIANGLE}
    -DEMBREE_GEOMETRY_QUAD=${EMBREE_GEOMETRY_QUAD}
    -DEMBREE_GEOMETRY_CURVE=${EMBREE_GEOMETRY_CURVE}
    -DEMBREE_GEOMETRY_SUBDIVISION=${EMBREE_GEOMETRY_SUBDIVISION}
    -DEMBREE_GEOMETRY_USER=${EMBREE_GEOMETRY_USER}
    -DEMBREE_GEOMETRY_POINT=${EMBREE_GEOMETRY_POINT}
    -DEMBREE_RAY_PACKETS=${EMBREE_RAY_PACKETS}
    -DEMBREE_MAX_INSTANCE_LEVEL_COUNT=${EMBREE_MAX_INSTANCE_LEVEL_COUNT}
    -DEMBREE_CURVE_SELF_INTERSECTION_AVOIDANCE_FACTOR=${EMBREE_CURVE_SELF_INTERSECTION_AVOIDANCE_FACTOR}
    -DEMBREE_MIN_WIDTH=${EMBREE_MIN_WIDTH})

ExternalProject_Add(
    ospray
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/ospray
    DEPENDS rkcommon embree OpenImageDenoise OpenVKL
    GIT_REPOSITORY https://github.com/ospray/ospray.git
    GIT_TAG v2.4.0
    GIT_SUBMODULES ""
    PATCH_COMMAND
        ${CMAKE_COMMAND} -E tar xf
        ${CMAKE_SOURCE_DIR}/ospray-patch.tar.gz
    CMAKE_ARGS ${ospray_ARGS})
